apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  # DopplerSecret Name
  name: spring-boot-app-doppler-secret

  # Namespace (only create DopplerSecret resources in the  doppler-operator-system namespace)
  namespace: doppler-operator-system

spec:
  tokenSecret:
    # Doppler token secret reference
    name: spring-boot-app-doppler-token

  managedSecret:
    # Synced secret name
    name: spring-boot-app-secret

    # Synced secret namespace (the namespace of the deployment that will consume this secret)
    namespace: default

  # Default 60 seconds. Low number used for demo purposes only.
  resyncSeconds: 5
